/**
 * Created by caeus on 25/06/17.
 */

export default {
    MAKE_QUERY: 'MAKE_QUERY',
    SET_QUERY_RESULTS: 'SET_QUERY_RESULTS',
    GET_COUNTRY: 'GET_COUNTRY',
    SET_COUNTRY: 'SET_COUNTRY',
    GET_AIRPORT_COUNTS_REPORT: 'GET_AIRPORT_COUNTS_REPORT',
    SET_AIRPORT_COUNTS_REPORT: 'SET_AIRPORT_COUNTS_REPORT',
    GET_HISTOGRAMS_REPORT: 'GET_HISTOGRAMS_REPORT',
    SET_HISTOGRAMS_REPORT: 'SET_HISTOGRAMS_REPORT',
    GET_MODES_REPORT: 'GET_MODES_REPORT',
    SET_MODES_REPORT: 'SET_MODES_REPORT',
    SET_ERROR:'SET_ERROR'
}